logging:
  level:
    com.oxyac: DEBUG

spring:
  jpa:
    show-sql: true
    database-platform: org.hibernate.dialect.H2Dialect
  datasource:
    url: jdbc:h2:mem:crm
    driverClassName: org.h2.Driver
    username: sa
  h2:
    console.enabled: true
