version: '3.1'

services:
  java:
    depends_on:
      - db
    build:
      context: .
    environment:
      BOT_NAME: $BOT_NAME
      BOT_TOKEN: $BOT_TOKEN
      BOT_DB_USERNAME: $BOT_DB_USERNAME
      BOT_DB_PASSWORD: $BOT_DB_PASSWORD
    restart: "no"
  db:
    image: mysql:5.7
    restart: always
    environment:
      MYSQL_USER: $BOT_DB_USERNAME
      MYSQL_PASSWORD: $BOT_DB_PASSWORD
      MYSQL_DATABASE: 'horaire'
      MYSQL_ROOT_PASSWORD: 'password'
    ports:
      - '3307:3306'
    expose:
      - '3306'
