server:
  port: ${PORT:8080}

logging:
  level:
    com.oxyac: ${LOG_LEVEL:INFO}

spring:
  jpa:
    show-sql: false
    database-platform: org.hibernate.dialect.H2Dialect
    hibernate:
      ddl-auto: create-drop
  datasource:
    url: jdbc:h2:${H2_DB_PATH:./horaire}
    driverClassName: org.h2.Driver
    username: sa

bot:
  name:  ${BOT_NAME}
  token: ${BOT_TOKEN}
