logging:
  level:
    com.oxyac: DEBUG

spring:
  jpa:
#    show-sql: true
    database: MYSQL
    hibernate:
      ddl-auto: update
  datasource:
    url: jdbc:mysql://localhost:3308/horaire
#    url: jdbc:mysql://db/horaire
    username: horaire
    password: horaire
  sql:
    init:
      mode: always

webdriver:
  firefox:
    driver: /usr/bin/geckodriver

bot:
  name: orar_lectii_bot
  token: 6194121912:AAEN1-0VES-J5AeykyBfWhQbkH-JOSrARcU

#bot:
#  name: ${BOT_NAME}
#  token: ${BOT_TOKEN}


#  #  jpa:
##    show-sql: true
##    database-platform: org.hibernate.dialect.H2Dialect
##  datasource:
##    url: jdbc:h2:mem:crm
##    driverClassName: org.h2.Driver
##    username: sa
##  h2:
##    console.enabled: true
